apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acquisitions

resources:
  - namespace.yaml
  - configmap.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - migration-job.yaml
  - pdb.yaml

images:
  - name: ghcr.io/pradnyan-khandakale/aquisitions
    newTag: tag-required
  - name: ghcr.io/pradnyan-khandakale/aquisitions-migration
    newTag: tag-required
